[bot]
profit_threshold_percent = 0.5
max_slippage_percent = 1.0
min_liquidity_usd = 10000
cooldown_seconds = 5
max_position_size_sol = 1.0
execute_trades = false
simulation_mode = true

[rpc]
solana_rpc_url = "https://alien-weathered-vineyard.solana-mainnet.quiknode.pro/1533e855c0eb19bb1ac93b1cd1d61c44c2db38b3"
solana_ws_url = "wss://alien-weathered-vineyard.solana-mainnet.quiknode.pro/1533e855c0eb19bb1ac93b1cd1d61c44c2db38b3"
max_requests_per_second = 10
burst_size = 20

[dexs]
enabled = ["orca", "raydium", "phoenix", "bitquery"]

[monitoring]
min_whale_transaction_sol = 10.0
mempool_enabled = true
whale_tracking_enabled = true
whale_wallet_addresses = []

[risk_management]
max_consecutive_losses = 5
daily_loss_limit_sol = 10.0
position_sizing_enabled = true
